### PR TITLE
support GET_PYTHON_MODULES - gather python module usage information

### PR DESCRIPTION
**Pull request by richm**
Run ansible with ANSIBLE_DEBUG=true and run each playbook with
PYTHONVERBOSE=1 in order to trace python module execution, so
that we can determine which python packages are required to run
each role.

### CODE REVIEW

**Comment by spetrosi** [comment]
[citest]

**Comment by richm** [comment]
[get_python_modules]

**Comment by richm** [comment]
[get_python_modules]

**Comment by richm** [comment]
[get_python_modules]

**Comment by richm** [comment]
[get_python_modules]

**Comment by richm** [comment]
[get_python_modules]

**Comment by richm** [comment]
[get_python_modules]

**Comment by richm** [comment]
[get_python_modules]

**Comment by richm** [comment]
[get_python_modules]

**Comment by richm** [comment]
[get_python_modules]

**Comment by richm** [comment]
[get_python_modules]

**Comment by richm** [comment]
@spetrosi can this be merged?

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
lgtm, postfix tests passed, you can merge

**Pull request merged**
