### PR TITLE
From lsrGetTests return full path to test playbooks

### PR DESCRIPTION
**Pull request by spetrosi**
* From lsrGetTests return full path to test playbooks
  By doing this, we can use full test playbook path to run playbooks regardless of the role in lsrGetRoleName
* In lsrRunPlaybooksParallel, add ability to write role_name to LOGFILE

### CODE REVIEW

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[get_python_modules]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Review by richm — APPROVED** [review]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Pull request merged**
