### PR TITLE
Add workflow to tun GET_PYTHON_MODULES against all roles

### PR DESCRIPTION
**Pull request by spetrosi**

### CODE REVIEW

**Comment by spetrosi** [comment]
@richm please take a look if this workflow needs to do anything special for https://github.com/linux-system-roles/tft-tests/pull/40

**Comment by spetrosi** [comment]
Not tested yet, I just hope that this should work. Once this is managed, we can add comment ``[get_python_modules]` to #40 and it will run on the PR

**Comment by spetrosi** [comment]
The best way to test this is to fork tft-tests, and in your fork, open a PR in reverse. I.e. do changed on the `main` branch, then open PR from `main` to any other branch. This way, the workflow still runs from the `main` branch, so from the branch where you do changes. You can try cherry-picking commits from #40 and #41 to your fork's branch and open a PR like I described.

**Comment by richm** [comment]
I don't think we need a separate workflow for this.  I have been testing with kernel_settings - https://github.com/linux-system-roles/kernel_settings/pull/226 - I add a comment like this: `[citest] GET_PYTHON_MODULES` - which will run the ci tests with `GET_PYTHON_MODULES=true` set.  This results in a .packages file for each "regular" log file.  https://dl.fedoraproject.org/pub/alt/linuxsystemroles/logs/tf_kernel_settings-226_CentOS-Stream-10-2.17_20240920-001352/artifacts/

I was planning to add a comment to the weekly_ci PRs - `[citest] GET_PYTHON_MODULES` - at first, just a one time thing

**Comment by richm** [comment]
The actual workflow change is https://github.com/linux-system-roles/kernel_settings/pull/225
Once I get the bugs worked out, I'll revert this

**Comment by spetrosi** [comment]
Rich implemented this elsewhere

**Pull request closed without merging**
